spring:
 application:
  name: Gbk2Mysql
# Configurações  do banco de dados Firebird
firebird:
 datasource:
  url:
   jdbc: firebirdsql://localhost:3050/firebird_db
   username: SYSDBA
   password: masterkey
   driver-class-name: org.firebirdsql.jdbc.FBDriver

# Configurações do banco de dados MySQL
mysql:
 datasource:
  url:
   jdbc: mysql://localhost:3306/mysql_db
   username: admin
   password: 1234
   driver-class-name: com.mysql.cj.jdbc.Driver
